### ISSUE TITLE
Invalid ConditionExpression: Attribute name is a reserved keyword; reserved keyword: date

### ISSUE THREAD

**Issue by kritish-dhaubanjar** [kritish-dhaubanjar/dynamodb-dashboard#264]
**Describe the bug**
Invalid ConditionExpression: Attribute name is a reserved keyword; reserved keyword: date when Restoring certain tables (dev_Metrics)

**To Reproduce**
1. Go to '/dynamodb/table/restore-tables'
2. Restore Tables

**Expected behavior**
- Restore Tables

**Screenshots**
![image](https://user-images.githubusercontent.com/25634165/221797961-ae8b86b5-5ddd-467e-ba8c-4e9bfd0fb660.png)

```
ValidationException: Invalid ConditionExpression: Attribute name is a reserved keyword; reserved keyword: date
    at throwDefaultError (/home/pi/.nvm/versions/node/v16.14.1/lib/node_modules/dynamodb-dashboard/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at deserializeAws_json1_0PutItemCommandError (/home/pi/.nvm/versions/node/v16.14.1/lib/node_modules/dynamodb-dashboard/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:2094:51)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/pi/.nvm/versions/node/v16.14.1/lib/node_modules/dynamodb-dashboard/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /home/pi/.nvm/versions/node/v16.14.1/lib/node_modules/dynamodb-dashboard/node_modules/@aws-sdk/lib-dynamodb/dist-cjs/baseCommand/DynamoDBDocumentClientCommand.js:26:34
    at async /home/pi/.nvm/versions/node/v16.14.1/lib/node_modules/dynamodb-dashboard/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at async /home/pi/.nvm/versions/node/v16.14.1/lib/node_modules/dynamodb-dashboard/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /home/pi/.nvm/versions/node/v16.14.1/lib/node_modules/dynamodb-dashboard/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'ca40aec7-f689-4698-9ef0-6b096c1876ce',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  __type: 'com.amazon.coral.validate#ValidationException'
}
```

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kritish-dhaubanjar** [comment]
`date` is reserved keyword of DynamoDB. Another is `type`. Not issue with UI.
